<?php


//add menu callback for each page
function passwordreminder_menu(){
	return array(
		'passwordreminder' => array(
			'title' => 'Password Reminder',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('passwordreminder_get_form'),
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
		),
	);
}

//specify template to use for the form (based on theme name)
function passwordreminder_theme(&$existing, $type, $theme, $path) {
	watchdog("passwordreminder", 'passwordreminder_theme', NULL, WATCHDOG_DEBUG);
	return array(
		'passwordremindertheme' => array(
			'template' => 'form-passwordreminder',
			'arguments' => array('form' => NULL),
		),
	);
}

//preprocess the form
function passwordreminder_preprocess_passwordremindertheme( &$vars ) { 
	watchdog("passwordreminder", 'passwordreminder_preprocess_passwordremindertheme', NULL, WATCHDOG_DEBUG);
	drupal_add_css(drupal_get_path('module', 'passwordreminder').'/passwordreminder.css');
	foreach( $vars['form'] as $k => $v ) {    
		if( preg_match( '/^[a-z]/', $k ) ) {      
			$vars[$k] = $vars['form'][$k];      
			unset( $vars['form'][$k] );    
		}  
	}
}


//create form elements
function passwordreminder_get_form(&$form){
	watchdog("passwordreminder", 'passwordreminder_get_form', NULL, WATCHDOG_DEBUG);	
	return array(
		'email' => array(
			'#type' => 'textfield', 
		),
		'submitbutton' => array(
			'#type' => 'submit',
			'#value' => 'SEND',
		),
		'#theme' => 'passwordremindertheme',
	);
}


/**/